joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

joint_trajectory_controller:
        type: pos_vel_controllers/JointTrajectoryController
        joints:
            - joint1
            - joint2
            - joint3